"""
This type stub file was generated by pyright.
"""

__all__ = ["GetJSONTypeOBJ", "GetClassFromCIM", "ConstructTypeObject"]
def getDateTimefromInt(dt): # -> datetime | None:
    ...

def GetClassFromCIM(class_name, module_name=...): # -> Any | None:
    ...

def DictToPoint(pt_dict): # -> Point:
    ...

def ConvertDataToArcpyData(cls, jsonObj): # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown] | Point:
    ...

def ConstructTypeObject(type_class, default_none=...):
    ...

def GetJSONTypeOBJ(json_obj): # -> Any | list[Unknown] | None:
    ...

