version: "0.2"
cache:
  cacheFormat: universal
  cacheStrategy: metadata
  useCache: true
allowCompoundWords: true
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - python
  - custom-dictionary
words: []
ignoreWords: []
import: []
languageSettings:
  - allowCompoundWords: true
    caseSensitive: false
    enabled: true
    languageId:
      - python
