"""
This type stub file was generated by pyright.
"""

from arcgisscripting import geocodingx as _geox

"Geocodex Module"
__all__ = ["Locator"]
class Locator(_geox.Locator):
  __slots__ = ...
  def __init__(self, path) -> None:
    ...
  


