"""
This type stub file was generated by pyright.
"""

from arcpy.geoprocessing._base import gptooldoc

r""""""
__all__ = ["QuickExport", "QuickImport"]
__alias__ = ...

@gptooldoc("QuickExport_FMEFunctionFactory", None)
def QuickExport():  # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """QuickExport_FMEFunctionFactory()"""
    ...

@gptooldoc("QuickImport_FMEFunctionFactory", None)
def QuickImport():  # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """QuickImport_FMEFunctionFactory()"""
    ...
