"""
This type stub file was generated by pyright.
"""

from arcpy.geoprocessing._base import gptooldoc

r"""The ArcGIS Indoor Positioning toolbox contains tools to create an
ArcGIS IPS Information Model, which enables indoor surveys with the
ArcGIS IPS Setup app, processing of survey data, and indoor
positioning. The toolbox also includes the Quality Assessment toolset
that contains tools to estimate the performance of an ArcGIS IPS
deployment."""
__all__ = ['ComputePositioningQuality', 'CreateIPSQualityDataset', 'EnableIndoorPositioning', 'GenerateIndoorPositioningFile']
__alias__ = ...
@gptooldoc('EnableIndoorPositioning_indoorpositioning', None)
def EnableIndoorPositioning(in_workspace=...): # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """EnableIndoorPositioning_indoorpositioning(in_workspace)

        Creates the feature classes and table necessary for storing ArcGIS IPS
        data in an existing geodatabase.

     INPUTS:
      in_workspace (Workspace):
          The geodatabase where the ArcGIS IPS table and feature classes will be
          created. It can be a file or enterprise geodatabase."""
    ...

@gptooldoc('GenerateIndoorPositioningFile_indoorpositioning', None)
def GenerateIndoorPositioningFile(in_ips_recordings=..., target_ips_positioning=..., in_ips_transitions=..., in_ips_comment=...): # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """GenerateIndoorPositioningFile_indoorpositioning(in_ips_recordings, target_ips_positioning, {in_ips_transitions}, {in_ips_comment})

        Generates a positioning file from ArcGIS IPS Setup survey recordings.

     INPUTS:
      in_ips_recordings (Feature Layer):
          The feature class or feature service that contains IPS Setup survey
          recordings.
      target_ips_positioning (Table View):
          The table or feature service where the generated IPS positioning file
          will be stored.
      in_ips_transitions {Feature Layer}:
          The line feature class that contains the TRANSITION_TYPE,
          VERTICAL_ORDER_FROM, and VERTICAL_ORDER_TO fields that define facility
          entrances and exits. These are used by ArcGIS IPS to improve indoor
          and outdoor localization and switching. The TRANSITION_TYPE field for
          entrances and exits must contain a value of 7 to be used by this tool.
      in_ips_comment {String}:
          The text that will be used to populate the Comment field of the
          positioning file entry in the target_ips_positioning value."""
    ...

@gptooldoc('ComputePositioningQuality_indoorpositioning', None)
def ComputePositioningQuality(target_ips_quality_dataset=..., in_ips_recordings_features=..., in_sight_blocking_details_features=...): # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """ComputePositioningQuality_indoorpositioning(target_ips_quality_dataset, in_ips_recordings_features, {in_sight_blocking_details_features})

        Populates an IPS Quality dataset generated by the Create IPS Quality
        Dataset tool.

     INPUTS:
      target_ips_quality_dataset (Dataset):
          The IPS Quality dataset generated by the Create IPS Quality Dataset
          tool that will be populated.
      in_ips_recordings_features (Feature Layer):
          The IPS Recordings feature layer that contains recordings collected
          using the ArcGIS IPS Setup app.
      in_sight_blocking_details_features {Feature Layer}:
          Details features from an Indoors dataset representing obstacles for
          line-of-sight calculation. It is recommended that you only use
          meaningful features, such as features that represent walls."""
    ...

@gptooldoc('CreateIPSQualityDataset_indoorpositioning', None)
def CreateIPSQualityDataset(target_workspace=..., coordinate_system=..., out_dataset_name=...): # -> conversion | int | float | complex | basestring | list[Unknown] | tuple[Unknown, ...] | dict[Unknown, Unknown]:
    """CreateIPSQualityDataset_indoorpositioning(target_workspace, coordinate_system, out_dataset_name)

        Creates a dataset that can be used to assess the quality of an ArcGIS
        IPS deployment.

     INPUTS:
      target_workspace (Workspace):
          The geodatabase where the ArcGIS IPS Quality dataset will be created.
          The value can be a file or an enterprise geodatabase.
      coordinate_system (Coordinate System):
          The spatial reference that will be used for the output IPS Quality
          dataset. The default is WGS84. You can specify the spatial reference
          in several ways, including the following:

          * Reference a feature class or feature dataset with the spatial
          reference you want to apply, such as
          C:/workspace/myproject.gdb/IPS_Recordings.

          * Use a SpatialReference object.

          * Use the well-known text (WKT) string of a spatial reference. One way
          to determine the WKT of a spatial reference is to export a
          SpatialReference object to a string using the exportToString method.
      out_dataset_name (String):
          The name of the dataset that will be created. The default is
          IPS_Quality."""
    ...

