"""
This type stub file was generated by pyright.
"""

from ._na._solvers import *
from ._na._rs import *
from ._na._cfs import *
from ._na._sas import *
from ._na._odcms import *
from ._na._las import *
from ._na._vrps import *
from ._na._nds import *

"""Work with network analysis functionality provided with ArcGIS Network Analyst extension."""
def ListDirectionsLanguages():
    """Return a List of supported directions language names."""
    ...

