"""
This type stub file was generated by pyright.
"""

from .CIMEnum import *
from .CIMExternal import *

class CIMGeneralPlacementProperties:
    """
    Represents general placement properties. This is base class for
    general placement properties for each label engine.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMLabelClass:
    """
    Represents a label class which describes how to generate a set
    of text labels from a group of features in a feature layer.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMLabelClassProperties:
    def __init__(self, *args, **Kwargs) -> None: ...

class CIMLabelPlacementProperties:
    """
    Represents label placement properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexDictionary:
    """
    Represents a Maplex dictionary.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexDictionaryEntry:
    """
    Represents a Maplex dictionary entry.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexExternalZonePriorities:
    """
    Represents Maplex external zone priorities.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexInternalZonePriorities:
    """
    Represents Maplex internal zone priorities.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexKeyNumberGroup:
    """
    Represents a Maplex key number group.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexLabelStackingProperties:
    """
    Represents Maplex label stacking properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexOffsetAlongLineProperties:
    """
    Represents Maplex offset along the line properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexRotationProperties:
    """
    Represents Maplex rotation properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexStackingSeparator:
    """
    Represents a Maplex stacking separator.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexStrategyPriorities:
    """
    Represents Maplex strategy priorities.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMStandardLineLabelPosition:
    """
    Represents standard label engine line label position.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMStandardLineLabelPriorities:
    """
    Represents standard label engine line label priorities.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMStandardPointPlacementPriorities:
    """
    Represents standard label engine point placement priorities.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexGeneralPlacementProperties(CIMGeneralPlacementProperties):
    """
    Represents Maplex general placement properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMMaplexLabelPlacementProperties(CIMLabelPlacementProperties):
    """
    Represents Maplex label placement properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMStandardGeneralPlacementProperties(CIMGeneralPlacementProperties):
    """
    Represents standard label engine general placement properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMStandardLabelPlacementProperties(CIMLabelPlacementProperties):
    """
    Represents standard label engine label placement properties.
    """

    def __init__(self, *args, **Kwargs) -> None: ...
