"""
This type stub file was generated by pyright.
"""

from .CIMEnum import *
from .CIMExternal import *
from .CIMLayer import CIMGroupLayer
from .CIMVectorLayers import CIMDataConnection

class CIMDiagramLayer(CIMGroupLayer):
    """
    Represents a diagram layer.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMDiagramRelQueryDataConnection(CIMDataConnection):
    """
    Represents a diagram rel query data connection.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMNetworkDiagramDataConnection(CIMDataConnection):
    """
    Represents a network diagram data connection.
    """

    def __init__(self, *args, **Kwargs) -> None: ...
