"""
This type stub file was generated by pyright.
"""

from .CIMEnum import *
from .CIMExternal import *
from .CIMCore import CIMDefinition

class CIMTimelineLayer:
    """
    Represents a layer in a timeline.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMTimelineSwimlane:
    """
    Represents a swimlane in a timeline.
    """

    def __init__(self, *args, **Kwargs) -> None: ...

class CIMTimeline(CIMDefinition):
    """
    Represents a timeline.
    """

    def __init__(self, *args, **Kwargs) -> None: ...
